theme: minima
title: Yousufs Recipes
author: Yousuf Farooqui
email: mfaro1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my cooking website where I show stolen recipes and act like its my own even though its not which is why I cite my sources
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
